<?php

namespace Modules\Contacts\Entities;

class Contact extends BaseModel
{
    protected $fillable = [
        'contact_auto_id',
        'contact_type',
        'contact_related',
        'name',
        'business_name',
        'total_employees',
        'phone',
        'landline',
        'email',
        'date_of_birth',
        'address',
        'shipping_address',
        'city',
        'state',
        'country',
        'zip_code',
        'status',
        'print_name',
        'nid_no',
        'additional_information',
        'print_ledger_code',
        'alternative_phone',
        'print_status',
        'permanent_address',
        'print_ledger_name',
        'billing_account',
        'description',
        'contact_status',
        'contact_mailing_name',
        'contact_post_office',
        'contact_police_station',
        'contact_currency',
        'contact_fax',
        'primary_mobile',
        'contact_send_sms',
        'contact_email',
        'mailing_name',
        'mailing_address',
        'mailing_email',
        'shipping_name',
        'shipping_number',
        'shipping_email',
        'shipping_send_sms',
        'alternative_address',
        'alternative_name',
        'alternative_post_office',
        'alternative_zip_code',
        'alternative_police_station',
        'alternative_state',
        'alternative_city',
        'alternative_fax',
        'alternative_send_sms',
        'alternative_email',
        'contact_file',
        'contact_document',
        'alternative_file',
        'tin_number',
        'tax_number',
        'tax_name',
        'tax_category',
        'tax_address',
        'bank_name',
        'bank_A_C_number',
        'bank_currency',
        'bank_branch',
        'contact_telephone',
        'trade_license_no',
        'known_person',
        'known_person_phone',
        'partner_name',
        'sales_team',
        'percentage',
        'created_by_id',
        'ref_id',
    ];

    public function contactRelatedPersone()
    {
        return $this->setConnection('crm')->hasMany(ContactPersonDetails::class, 'contact_id');
    }
}
